apiVersion: v1
kind: Secret
metadata:
  name: mariadb-root-secret
type: Opaque
stringData:
  root-password: "RootStrongPass123!"
  database: "appdb"
  user: "appuser"
  password: "AppPassw0rd"